CREATE TABLE Reports (
    REPORT_ID NUMERIC(9) NOT NULL,
    REPORT_NO VARCHAR(9) NOT NULL,
    VERSION_NO NUMERIC(3) NOT NULL,
    DATRECEIVED DATE,
    DATINTRECEIVED DATE,
    MAH_NO VARCHAR(20),
    REPORT_TYPE_CODE VARCHAR(9),
    REPORT_TYPE_ENG VARCHAR(60),
    REPORT_TYPE_FR VARCHAR(60),
    GENDER_CODE VARCHAR(9),
    GENDER_ENG VARCHAR(60),
    GENDER_FR VARCHAR(60),
    AGE NUMERIC(6,3),
    AGE_Y NUMERIC(6,3),
    AGE_UNIT_ENG VARCHAR(60),
    AGE_UNIT_FR VARCHAR(60),
    OUTCOME_CODE VARCHAR(9),
    OUTCOME_ENG VARCHAR(60),
    OUTCOME_FR VARCHAR(60),
    WEIGHT NUMERIC(7,3),
    WEIGHT_UNIT_ENG VARCHAR(60),
    WEIGHT_UNIT_FR VARCHAR(60),
    HEIGHT NUMERIC(7,3),
    HEIGHT_UNIT_ENG VARCHAR(60),
    HEIGHT_UNIT_FR VARCHAR(60),
    SERIOUSNESS_CODE VARCHAR(9),
    SERIOUSNESS_ENG VARCHAR(60),
    SERIOUSNESS_FR VARCHAR(60),
    DEATH VARCHAR(9),
    DISABILITY VARCHAR(9),
    CONGENITAL_ANOMALY VARCHAR(9),
    LIFE_THREATENING VARCHAR(9),
    HOSP_REQUIRED VARCHAR(9),
    OTHER_MEDICALLY_IMP_COND VARCHAR(9),
    REPORTER_TYPE_ENG VARCHAR(60),
    REPORTER_TYPE_FR VARCHAR(60),
    SOURCE_CODE VARCHAR(9),
    SOURCE_ENG VARCHAR(60),
    SOURCE_FR VARCHAR(60),
    E2B_IMP_SAFETYREPORT_ID VARCHAR(100),
    AUTHORITY_NUMB VARCHAR(100),
    COMPANY_NUMB VARCHAR(100),
    PRIMARY KEY (REPORT_ID)
);

ALTER TABLE Reports
ADD CONSTRAINT unique_report_no UNIQUE (report_no);

CREATE TABLE Drug_Product (
    DRUG_PRODUCT_ID NUMERIC(8) NOT NULL,
    DRUGNAME VARCHAR(1000),
    PRIMARY KEY (DRUG_PRODUCT_ID)
);

CREATE TABLE Drug_Product_Ingredients (
    DRUG_PRODUCT_INGREDIENT_ID NUMERIC(15) NOT NULL,
    DRUG_PRODUCT_ID NUMERIC(8),
    DRUGNAME VARCHAR(1000),
    ACTIVE_INGREDIENT_ID NUMERIC(8),
    ACTIVE_INGREDIENT_NAME VARCHAR(400),
    PRIMARY KEY (DRUG_PRODUCT_INGREDIENT_ID),
    FOREIGN KEY (DRUG_PRODUCT_ID) REFERENCES Drug_Product(DRUG_PRODUCT_ID)
);

CREATE TABLE Reactions (
    REACTION_ID NUMERIC NOT NULL,
    REPORT_ID VARCHAR(9),
    DURATION NUMERIC(9,3),
    DURATION_UNIT_ENG VARCHAR(60),
    DURATION_UNIT_FR VARCHAR(60),
    PT_NAME_ENG VARCHAR(250),
    PT_NAME_FR VARCHAR(250),
    SOC_NAME_ENG VARCHAR(250),
    SOC_NAME_FR VARCHAR(250),
    MEDDRA_VERSION VARCHAR(9),
    PRIMARY KEY (REACTION_ID),
    FOREIGN KEY (REPORT_ID) REFERENCES Reports(REPORT_NO)
);

CREATE TABLE Outcome_LX (
    OUTCOME_LX_ID NUMERIC(4) NOT NULL,
    OUTCOME_CODE VARCHAR(3),
    OUTCOME_EN VARCHAR(60),
    OUTCOME_FR VARCHAR(60),
    PRIMARY KEY (OUTCOME_LX_ID)
);

CREATE TABLE Gender_LX (
    GENDER_LX_ID NUMERIC(7) NOT NULL,
    GENDER_CODE VARCHAR(9),
    GENDER_EN VARCHAR(60),
    GENDER_FR VARCHAR(60),
    PRIMARY KEY (GENDER_LX_ID)
);

CREATE TABLE Report_Type_LX (
    REPORT_TYPE_LX_ID NUMERIC(7) NOT NULL,
    REPORT_TYPE_CODE VARCHAR(9),
    REPORT_TYPE_EN VARCHAR(60),
    REPORT_TYPE_FR VARCHAR(60),
    PRIMARY KEY (REPORT_TYPE_LX_ID)
);

CREATE TABLE Seriousness_LX (
    SERIOUSNESS_LX_ID NUMERIC(7) NOT NULL,
    SERIOUSNESS_CODE VARCHAR(9),
    SERIOUSNESS_EN VARCHAR(60),
    SERIOUSNESS_FR VARCHAR(60),
    PRIMARY KEY (SERIOUSNESS_LX_ID)
);

CREATE TABLE Source_LX (
    SOURCE_LX_ID NUMERIC(7) NOT NULL,
    SOURCE_CODE VARCHAR(9),
    SOURCE_EN VARCHAR(60),
    SOURCE_FR VARCHAR(60),
    PRIMARY KEY (SOURCE_LX_ID)
);

CREATE TABLE Report_Links_LX (
    REPORT_LINK_ID NUMERIC NOT NULL,
    REPORT_ID NUMERIC NOT NULL,
    RECORD_TYPE_ENG VARCHAR(9),
    RECORD_TYPE_FR VARCHAR(7),
    REPORT_LINK_NO VARCHAR(18),
    PRIMARY KEY (REPORT_LINK_ID),
    FOREIGN KEY (REPORT_ID) REFERENCES Reports(REPORT_ID)
);

CREATE TABLE Report_Drug (
    REPORT_DRUG_ID NUMERIC(15) NOT NULL,
    REPORT_ID NUMERIC(15),
    DRUG_PRODUCT_ID NUMERIC(8),
    DRUGNAME VARCHAR(1000),
    DRUGINVOLV_ENG VARCHAR(300),
    DRUGINVOLV_FR VARCHAR(300),
    ROUTEADMIN_ENG VARCHAR(300),
    ROUTEADMIN_FR VARCHAR(300),
    UNIT_DOSE_QTY NUMERIC(20,9),
    DOSE_UNIT_ENG VARCHAR(300),
    DOSE_UNIT_FR VARCHAR(300),
    FREQUENCY NUMERIC(3),
    FREQ_TIME NUMERIC(10,5),
    FREQUENCY_TIME_ENG VARCHAR(30),
    FREQUENCY_TIME_FR VARCHAR(30),
    FREQ_TIME_UNIT_ENG VARCHAR(300),
    FREQ_TIME_UNIT_FR VARCHAR(300),
    THERAPY_DURATION NUMERIC(10,5),
    THERAPY_DURATION_UNIT_ENG VARCHAR(300),
    THERAPY_DURATION_UNIT_FR VARCHAR(300),
    DOSAGEFORM_ENG VARCHAR(300),
    DOSAGEFORM_FR VARCHAR(300),
    PRIMARY KEY (REPORT_DRUG_ID),
    FOREIGN KEY (REPORT_ID) REFERENCES Reports(REPORT_ID),
    FOREIGN KEY (DRUG_PRODUCT_ID) REFERENCES Drug_Product(DRUG_PRODUCT_ID)
);

CREATE TABLE Report_Drug_Indication (
    REPORT_DRUG_ID NUMERIC(15) NOT NULL,
    REPORT_ID NUMERIC(15),
    DRUG_PRODUCT_ID NUMERIC(8),
    DRUGNAME VARCHAR(1000),
    INDICATION_NAME_ENG VARCHAR(250),
    INDICATION_NAME_FR VARCHAR(250),
    PRIMARY KEY (REPORT_DRUG_ID),
    FOREIGN KEY (REPORT_ID) REFERENCES Reports(REPORT_ID),
    FOREIGN KEY (DRUG_PRODUCT_ID) REFERENCES Drug_Product(DRUG_PRODUCT_ID)
);

CREATE TABLE Literature_Reference (
    REPORT_ID NUMERIC NOT NULL,
    REPORT_NO VARCHAR(9) NOT NULL,
    VERSION_NO NUMERIC(3) NOT NULL,
    SEQ_LITERATURE NUMERIC(4),
    LITERATURE_REFERENCE VARCHAR(1000),
    PRIMARY KEY (REPORT_ID, REPORT_NO, VERSION_NO),
    FOREIGN KEY (REPORT_ID) REFERENCES Reports(REPORT_ID)
);


-- DROP TABLE Literature_Reference;
-- DROP TABLE Report_Drug_Indication;
-- DROP TABLE Report_Drug;
-- DROP TABLE Report_Links_LX;
-- DROP TABLE Source_LX;
-- DROP TABLE Seriousness_LX;
-- DROP TABLE Report_Type_LX;
-- DROP TABLE Gender_LX;
-- DROP TABLE Outcome_LX;
-- DROP TABLE Reactions;
-- DROP TABLE Drug_Product_Ingredients;
-- DROP TABLE Drug_Product;
-- DROP TABLE Reports;
